/gate/digitizer/Singles/insert                        opticaladder
/gate/digitizer/Singles/insert                        adder
/gate/digitizer/Singles/insert                        readout
/gate/digitizer/Singles/readout/setDepth              1

/gate/digitizer/Singles/insert                        blurring
/gate/digitizer/Singles/blurring/setResolution        0.26
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

/gate/digitizer/Singles/insert                        thresholder
/gate/digitizer/Singles/thresholder/setThreshold      350. keV
/gate/digitizer/Singles/insert                        upholder
/gate/digitizer/Singles/upholder/setUphold            650. keV
