/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel
#/gate/physics/processes/PhotoElectric/setModel LivermoreModel
#/gate/physics/processes/PhotoElectric/setModel PenelopeModel
#/gate/physics/processes/PhotoElectric/setAugerElectron true

#/gate/physics/addAtomDeexcitation


#/gate/physics/Gamma/SetCutInRegion      scanner  0.1 mm
#/gate/physics/Electron/SetCutInRegion   scanner  0.1 mm
#/gate/physics/Positron/SetCutInRegion   scanner  0.1 mm


#/gate/physics/Gamma/SetCutInRegion      scanner  0.0001 mm
#/gate/physics/Electron/SetCutInRegion   scanner  0.01 mm
#/gate/physics/Positron/SetCutInRegion   scanner  0.01 mm

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel
#/gate/physics/processes/Compton/setModel PenelopeModel


#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel StandardModel
#/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
#/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.1 0.1 mm
#/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.1 0.1 mm

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+


#/gate/physics/addProcess PositronAnnihilation

#/gate/physics/addProcess MultipleScattering e+
#/gate/physics/addProcess MultipleScattering e-

#/gate/physics/processList Enabled
#/gate/physics/processList Initialized

/gate/physics/addProcess OpticalAbsorption
/gate/physics/addProcess OpticalRayleigh
/gate/physics/addProcess OpticalBoundary
/gate/physics/addProcess OpticalMie
/gate/physics/addProcess OpticalWLS
/gate/physics/addProcess Scintillation

/gate/physics/processList Enabled
/gate/physics/processList Initialized
